const challenges = [
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 1',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 2',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 3',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 4',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 5',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 6',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 7',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 8',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 9',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 10',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 11',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 1',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 2',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 3',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 4',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 5',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 6',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 7',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 8',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 9',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 10',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 11',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Challenging America geo prediction',
        describe: 'Guess publication location for a piece of text',
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 1',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 2',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 3',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 4',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 5',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 6',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 7',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '2 hours',
    },
    {
        title: 'Example 8',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '55%',
        prize: '5000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 9',
        describe: 'Guess publication location for a piece of text',
        type: 'text',
        metric: 'Haversine',
        bestScore: '79%',
        baseline: '60%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 10',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'image',
        metric: 'Haversine',
        bestScore: '90%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    },
    {
        title: 'Example 11',
        describe: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis nunc odio, 
        ut lacinia mi vestibulum eget. Donec non tellus lorem. Aliquam maximus semper accumsan.`,
        type: 'tabular',
        metric: 'RMSE',
        bestScore: '79%',
        baseline: '55%',
        prize: '150000 PLN',
        timeLeft: '6 days',
    }
]

export default challenges;