version: '3.7'
services:
  gonito:
    container_name: gonito_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_KC_URL=${REACT_APP_KC_URL}
      - REACT_APP_KC_REALM=${REACT_APP_KC_REALM}
      - REACT_APP_KC_CLIENT_ID=${REACT_APP_KC_CLIENT_ID}
    volumes:
     - .:/app
     - /app/node_modules
